### PR TITLE
Evernote Data Saved to Database, API Usage Reduced by 50%, and more

### PR DESCRIPTION
**Pull request by holycrepe**
1. All Evernote data saved to database
2. Since Tags are saved locally, we don't need to query Evernote for them. This reduces API usage by 50%
3. Notes that are already in sync with Evernote's servers won't update
4. Generate Anki deck name from Evernote notebook name
5. Anknotes detects links between notes and creates table of contents pages for linked notes. This is an advanced function that will likely require some documentation before it can be widely used by the general public.

### CODE REVIEW

**Comment by holycrepe** [comment]
Hey, I made some significant changes to the Models (Note Types) used by anknotes. I haven't tested to see if they are automatically generated without errors so there may be some issues with that. However, if you manually setup the Models, it works flawlessly. 

I'll look into automating initial setup of the Models if there's interest. In the more distant future, I will write up some documentation about how to use the Table of Contents functionality, which is very useful if you have lots of notes that are interconnected, and you utilize Evernote's Note Links to link between notes.

**Comment by brumar** [comment]
Hi ! It seems there are a lot of cool improvements in this pull request ! I won't have time to test this until 10 days or so, but I will look at it whenever I have time. Thanks for the contributions.! Bruno

**Comment by Scriptkiddi** [comment]
sorry about the delay but I only found the time today and I commented on the pull request on my forked so its in progess

**Comment by Scriptkiddi** [comment]
maybe we should by this way just add me and @holycrepe to your repo @brumar  then we would not have the problem of having 3 forks with their own pull requests and issues what do you think about it?

**Comment by brumar** [comment]
Yes, this is by far the best thing to do.
I'd be happy to enable it.
However I lack experience in this mode of collaboration.
Do you have any guidelines ? Shall we set up some rules ?
I would suggest to work with 2 branches (production and developement). 
What do you think ?

**Comment by holycrepe** [comment]
I think merging into one repo with each developer having their own dev branch is a great idea! I for one have a few features that are not going to be useful for the general public or a production branch right now, so having dev vs production branches would certainly be useful.

I just read @Scriptkiddi's notes and am looking into it now. I've also joined Trello. Looking forward to our future collaboration and creating something that can be pushed to Evernote and Anki's addon repositories for use of the general public!

**Comment by holycrepe** [comment]
I'm not seeing any references to generateTocTitle, but I haven't committed latest changes. So, I pushed an up-to-date commit to my repo, let me know if that works for you. Most of my dealings with titles/strings are hackish, as I don't know how to deal with unicode properly in Python and have been getting lots of issues that I've got around in ways I can only think are noobish if one had experience with Python. So I would appreciate any comments as to how I could improve the code related to handling unicode, and just Python coding practices in general.

**Comment by Scriptkiddi** [comment]
Hey i think you push is not working last change in your repo was 7 days ago

best wishes

Fritz

**Comment by holycrepe** [comment]
Oh I changed branch aip1000 to master a few days ago so I wouldn't have to keep making pull requests into master. I'll make a new pull request for your branch and close this one. I also squashed a few bugs so get the latest commit from today

**Comment by holycrepe** [comment]
Or instead of a new pull request should we start using new dev branches on @brumar's repo?

**Comment by holycrepe** [comment]
Hey I fixed another bug and pushed update to newly created branch holycrepe on this repo. Also I updated the readme with all the new functionality. This may be useful for both of you as I also included some [developer notes] (https://github.com/brumar/anknotes/tree/holycrepe#developer-notes). 

I'll submit an updated pull request now. I'm fairly confident everything should be working, but see also footer links are not 100% complete. Still ironing out the kinks of detecting changes and uploading to Evernote servers.

**Pull request merged**
