### PR TITLE
Aip1000

### PR DESCRIPTION
**Pull request by aip1000**

### CODE REVIEW

**Comment by brumar** [comment]
Congrats to you and @Scriptkiddi for the amazing work. I can't merge it automatically, but I will figure the all thing out tomorrow.

**Comment by brumar** [comment]
I just tested and got this error :  
```
 File "C:\Users\Nevrose\Documents\Anki\addons\anknotes\__main__.py", line 47, in add_note
    collection.addNote(note)
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.collection", line 253, in addNote
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.notes", line 50, in flush
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.notes", line 113, in stringTags
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.tags", line 149, in canonify
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/re", line 151, in sub
TypeError: expected string or buffer
```
It sounds like it's caused by empty tag or list of tags, do you have any idea where would it come from ?

**Comment by aip1000** [comment]
Most of the work was scriptkiddi's! I just updated to properly save tags, and update new Evernote notes by deleting the original Anki note and re-adding it. 

I actually made this pull request by error; I was meaning to make a pull request from my fork to Scriptkiddi's. I would suggest waiting a day or two for Scriptkiddi to update his fork, and we can debug your error. 

In the meantime can you add a showInfo() with all of note's attributes? Maybe something will come up as a list that should be a string

**Comment by Scriptkiddi** [comment]
i will have a look tomorrow

**Comment by Scriptkiddi** [comment]
brumar could you test the branch aip1000 which should work fine

**Pull request merged**
